"""atualiza tabela com modelo de str para text

Revision ID: 1539c97f7142
Revises: 6f6730472b7f
Create Date: 2025-09-23 08:44:05.514958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1539c97f7142'
down_revision: Union[str, Sequence[str], None] = '6f6730472b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('text_modelo', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propostas', 'text_modelo')
    # ### end Alembic commands ###
