"""add xml column

Revision ID: 31d529b580f4
Revises: 975e369262f5
Create Date: 2025-09-16 10:25:05.149207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d529b580f4'
down_revision: Union[str, Sequence[str], None] = '975e369262f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('xml', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propostas', 'xml')
    # ### end Alembic commands ###
