"""atualiza tabela com modelo de str para text

Revision ID: 610c1decbc25
Revises: 1539c97f7142
Create Date: 2025-09-23 11:54:45.385755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610c1decbc25'
down_revision: Union[str, Sequence[str], None] = '1539c97f7142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('propostas', 'text_modelo',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=700),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('propostas', 'text_modelo',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###
