"""add cancelada e emidita dt

Revision ID: 6f6730472b7f
Revises: a3cf69fe0eed
Create Date: 2025-09-17 15:07:19.918328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6730472b7f'
down_revision: Union[str, Sequence[str], None] = 'a3cf69fe0eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('emitida_em', sa.DateTime(), nullable=True))
    op.add_column('propostas', sa.Column('cancelada_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propostas', 'cancelada_em')
    op.drop_column('propostas', 'emitida_em')
    # ### end Alembic commands ###
