"""Add fields for D4Sign integration

Revision ID: 8485e9dd7964
Revises: 3b3f3e292957
Create Date: 2025-09-24 11:32:24.875966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8485e9dd7964'
down_revision: Union[str, Sequence[str], None] = '3b3f3e292957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apolices', sa.Column('pdf_assinado', sa.LargeBinary(), nullable=True))
    op.add_column('apolices', sa.Column('d4sign_document_id', sa.String(length=100), nullable=True))
    op.add_column('apolices', sa.Column('status_assinatura', sa.String(length=20), nullable=True))
    op.drop_column('apolices', 'pdf_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apolices', sa.Column('pdf_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('apolices', 'status_assinatura')
    op.drop_column('apolices', 'd4sign_document_id')
    op.drop_column('apolices', 'pdf_assinado')
    # ### end Alembic commands ###
