"""initial

Revision ID: c6d043fede19
Revises: 
Create Date: 2025-10-01 10:42:42.756422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d043fede19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_finances_id'), 'finances', ['id'], unique=False)
    op.create_table('segurados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('fantasia', sa.String(length=255), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_index(op.f('ix_segurados_id'), 'segurados', ['id'], unique=False)
    op.create_table('assessorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('comissao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['finance_id'], ['finances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_assessorias_id'), 'assessorias', ['id'], unique=False)
    op.create_table('corretoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('inscricao_municipal', sa.String(length=50), nullable=True),
    sa.Column('comissao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('situacao_cnpj', sa.String(length=50), nullable=True),
    sa.Column('codigo_cnae', sa.String(length=20), nullable=True),
    sa.Column('ramo', sa.String(length=100), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_recadastro', sa.Date(), nullable=True),
    sa.Column('data_expiracao', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('tipo_conta', sa.String(length=50), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('digito_agencia', sa.String(length=5), nullable=True),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('digito_conta', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['finance_id'], ['finances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_corretoras_id'), 'corretoras', ['id'], unique=False)
    op.create_table('documentos_assessoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessoria_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessoria_id'], ['assessorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_assessoria_id'), 'documentos_assessoria', ['id'], unique=False)
    op.create_table('documentos_corretora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corretora_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_corretora_id'), 'documentos_corretora', ['id'], unique=False)
    op.create_table('responsaveis_financeiros_corretora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corretora_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsaveis_financeiros_corretora_id'), 'responsaveis_financeiros_corretora', ['id'], unique=False)
    op.create_table('socios_corretora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corretora_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socios_corretora_id'), 'socios_corretora', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('finance_id', sa.Integer(), nullable=True),
    sa.Column('corretora_id', sa.Integer(), nullable=True),
    sa.Column('assessoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessoria_id'], ['assessorias.id'], ),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretoras.id'], ),
    sa.ForeignKeyConstraint(['finance_id'], ['finances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('tomadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('fantasia', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('capital_social', sa.Float(), nullable=True),
    sa.Column('limite_aprovado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('limite_disponivel', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_tomadores_id'), 'tomadores', ['id'], unique=False)
    op.create_table('clientes_asaas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('tomador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tomador_id'], ['tomadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index(op.f('ix_clientes_asaas_id'), 'clientes_asaas', ['id'], unique=False)
    op.create_table('propostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('subgrupo', sa.String(length=100), nullable=True),
    sa.Column('importancia_segurada', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('termino_vigencia', sa.Date(), nullable=True),
    sa.Column('dias_vigencia', sa.Integer(), nullable=True),
    sa.Column('emitida_em', sa.DateTime(), nullable=True),
    sa.Column('cancelada_em', sa.DateTime(), nullable=True),
    sa.Column('taxa_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('premio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comissao_valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('numero_contrato', sa.String(length=50), nullable=True),
    sa.Column('edital_processo', sa.String(length=100), nullable=True),
    sa.Column('percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('text_modelo', sa.String(length=700), nullable=True),
    sa.Column('link_pagamento', sa.String(), nullable=True),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('tomador_id', sa.Integer(), nullable=True),
    sa.Column('segurado_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segurado_id'], ['segurados.id'], ),
    sa.ForeignKeyConstraint(['tomador_id'], ['tomadores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_propostas_id'), 'propostas', ['id'], unique=False)
    op.create_table('apolices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('pdf_assinado', sa.LargeBinary(), nullable=True),
    sa.Column('d4sign_document_id', sa.String(length=100), nullable=True),
    sa.Column('status_assinatura', sa.String(length=20), nullable=True),
    sa.Column('proposta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_apolices_id'), 'apolices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apolices_id'), table_name='apolices')
    op.drop_table('apolices')
    op.drop_index(op.f('ix_propostas_id'), table_name='propostas')
    op.drop_table('propostas')
    op.drop_index(op.f('ix_clientes_asaas_id'), table_name='clientes_asaas')
    op.drop_table('clientes_asaas')
    op.drop_index(op.f('ix_tomadores_id'), table_name='tomadores')
    op.drop_table('tomadores')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_socios_corretora_id'), table_name='socios_corretora')
    op.drop_table('socios_corretora')
    op.drop_index(op.f('ix_responsaveis_financeiros_corretora_id'), table_name='responsaveis_financeiros_corretora')
    op.drop_table('responsaveis_financeiros_corretora')
    op.drop_index(op.f('ix_documentos_corretora_id'), table_name='documentos_corretora')
    op.drop_table('documentos_corretora')
    op.drop_index(op.f('ix_documentos_assessoria_id'), table_name='documentos_assessoria')
    op.drop_table('documentos_assessoria')
    op.drop_index(op.f('ix_corretoras_id'), table_name='corretoras')
    op.drop_table('corretoras')
    op.drop_index(op.f('ix_assessorias_id'), table_name='assessorias')
    op.drop_table('assessorias')
    op.drop_index(op.f('ix_segurados_id'), table_name='segurados')
    op.drop_table('segurados')
    op.drop_index(op.f('ix_finances_id'), table_name='finances')
    op.drop_table('finances')
    # ### end Alembic commands ###
