"""add novos dados tomador

Revision ID: c6dc05f199da
Revises: 1bee77a4b3e5
Create Date: 2025-09-26 15:12:25.418834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6dc05f199da'
down_revision: Union[str, Sequence[str], None] = '1bee77a4b3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tomadores', sa.Column('limite_aprovado', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tomadores', sa.Column('limite_disponivel', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_column('tomadores', 'limite_taxa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tomadores', sa.Column('limite_taxa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('tomadores', 'limite_disponivel')
    op.drop_column('tomadores', 'limite_aprovado')
    # ### end Alembic commands ###
