"""Atualiza tabela segurados com novos campos

Revision ID: f01e7556abe6
Revises: ba767a4d05c5
Create Date: 2025-09-15 09:38:51.613804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01e7556abe6'
down_revision: Union[str, Sequence[str], None] = 'ba767a4d05c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segurados', sa.Column('fantasia', sa.String(length=255), nullable=True))
    op.add_column('segurados', sa.Column('logradouro', sa.String(length=255), nullable=True))
    op.add_column('segurados', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('segurados', sa.Column('complemento', sa.String(length=255), nullable=True))
    op.add_column('segurados', sa.Column('bairro', sa.String(length=100), nullable=True))
    op.drop_column('segurados', 'endereco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segurados', sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('segurados', 'bairro')
    op.drop_column('segurados', 'complemento')
    op.drop_column('segurados', 'numero')
    op.drop_column('segurados', 'logradouro')
    op.drop_column('segurados', 'fantasia')
    # ### end Alembic commands ###
