"""add campos pagamento em proposta

Revision ID: 3b3f3e292957
Revises: 4283a571f1dc
Create Date: 2025-09-24 09:12:32.439261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3f3e292957'
down_revision: Union[str, Sequence[str], None] = '4283a571f1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('link_pagamento', sa.String(), nullable=True))
    op.add_column('propostas', sa.Column('pago_em', sa.DateTime(), nullable=True))
    op.add_column('propostas', sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propostas', 'valor_pago')
    op.drop_column('propostas', 'pago_em')
    op.drop_column('propostas', 'link_pagamento')
    # ### end Alembic commands ###
