"""atualiza tabela com table do asaas cliente

Revision ID: 4283a571f1dc
Revises: 610c1decbc25
Create Date: 2025-09-23 14:20:27.667255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4283a571f1dc'
down_revision: Union[str, Sequence[str], None] = '610c1decbc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_asaas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('tomador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tomador_id'], ['tomadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index(op.f('ix_clientes_asaas_id'), 'clientes_asaas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_asaas_id'), table_name='clientes_asaas')
    op.drop_table('clientes_asaas')
    # ### end Alembic commands ###
