"""Atualiza tabela propostas

Revision ID: 975e369262f5
Revises: f01e7556abe6
Create Date: 2025-09-16 10:12:38.052766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975e369262f5'
down_revision: Union[str, Sequence[str], None] = 'f01e7556abe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('taxa_percentual', sa.Float(), nullable=False))
    op.add_column('propostas', sa.Column('comissao_percentual', sa.Float(), nullable=False))
    op.add_column('propostas', sa.Column('comissao_valor', sa.Float(), nullable=True))
    op.add_column('propostas', sa.Column('edital_processo', sa.String(length=100), nullable=True))
    op.add_column('propostas', sa.Column('percentual', sa.Float(), nullable=True))
    op.alter_column('propostas', 'data_criacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('propostas', 'numero_contrato',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('propostas', 'comissao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('comissao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('propostas', 'numero_contrato',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('propostas', 'data_criacao',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('propostas', 'percentual')
    op.drop_column('propostas', 'edital_processo')
    op.drop_column('propostas', 'comissao_valor')
    op.drop_column('propostas', 'comissao_percentual')
    op.drop_column('propostas', 'taxa_percentual')
    # ### end Alembic commands ###
