"""add tabelas novas

Revision ID: ef039353d606
Revises: 8485e9dd7964
Create Date: 2025-09-25 14:51:44.483630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef039353d606'
down_revision: Union[str, Sequence[str], None] = '8485e9dd7964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_finances_id'), 'finances', ['id'], unique=False)
    op.create_table('assessorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('comissao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['finance_id'], ['finances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_assessorias_id'), 'assessorias', ['id'], unique=False)
    op.create_table('corretoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('inscricao_municipal', sa.String(length=50), nullable=True),
    sa.Column('comissao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('situacao_cnpj', sa.String(length=50), nullable=True),
    sa.Column('codigo_cnae', sa.String(length=20), nullable=True),
    sa.Column('ramo', sa.String(length=100), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_recadastro', sa.Date(), nullable=True),
    sa.Column('data_expiracao', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('tipo_conta', sa.String(length=50), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('digito_agencia', sa.String(length=5), nullable=True),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('digito_conta', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['finance_id'], ['finances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_corretoras_id'), 'corretoras', ['id'], unique=False)
    op.create_table('documentos_assessoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessoria_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessoria_id'], ['assessorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_assessoria_id'), 'documentos_assessoria', ['id'], unique=False)
    op.create_table('documentos_corretora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corretora_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_corretora_id'), 'documentos_corretora', ['id'], unique=False)
    op.create_table('responsaveis_financeiros_corretora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corretora_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsaveis_financeiros_corretora_id'), 'responsaveis_financeiros_corretora', ['id'], unique=False)
    op.create_table('socios_corretora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corretora_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socios_corretora_id'), 'socios_corretora', ['id'], unique=False)
    op.add_column('tomadores', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tomadores', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('usuarios', sa.Column('finance_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('corretora_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('assessoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'corretoras', ['corretora_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'finances', ['finance_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'assessorias', ['assessoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'assessoria_id')
    op.drop_column('usuarios', 'corretora_id')
    op.drop_column('usuarios', 'finance_id')
    op.drop_constraint(None, 'tomadores', type_='foreignkey')
    op.drop_column('tomadores', 'usuario_id')
    op.drop_index(op.f('ix_socios_corretora_id'), table_name='socios_corretora')
    op.drop_table('socios_corretora')
    op.drop_index(op.f('ix_responsaveis_financeiros_corretora_id'), table_name='responsaveis_financeiros_corretora')
    op.drop_table('responsaveis_financeiros_corretora')
    op.drop_index(op.f('ix_documentos_corretora_id'), table_name='documentos_corretora')
    op.drop_table('documentos_corretora')
    op.drop_index(op.f('ix_documentos_assessoria_id'), table_name='documentos_assessoria')
    op.drop_table('documentos_assessoria')
    op.drop_index(op.f('ix_corretoras_id'), table_name='corretoras')
    op.drop_table('corretoras')
    op.drop_index(op.f('ix_assessorias_id'), table_name='assessorias')
    op.drop_table('assessorias')
    op.drop_index(op.f('ix_finances_id'), table_name='finances')
    op.drop_table('finances')
    # ### end Alembic commands ###
